### ISSUE TITLE
1.0.3版本import引入不识别

### ISSUE THREAD

**Issue by yuzihan30** [gitboyzcf/vite-plugin-style-vw-loader#2]
![1695291588796](https://github.com/gitboyzcf/vite-plugin-style-vw-loader/assets/9654867/0a83e493-1e3a-4a3c-9b33-d30b72605e9d)

**Comment by gitboyzcf** [comment]
在.d.ts文件中声明下这个模块
`declare module "vite-plugin-style-vw-loader";`
