### ISSUE TITLE
vue3组件内行内样式从px转vw没生效

### ISSUE THREAD

**Issue by yuzihan30** [gitboyzcf/vite-plugin-style-vw-loader#3]
declare module "vite-plugin-style-vw-loader";
这个加了之后识别了
但行内样式从px转vw没生效
![1696939197036](https://github.com/gitboyzcf/vite-plugin-style-vw-loader/assets/9654867/8c9866c0-54b1-4f05-bab3-dc0731fc567d)
![1696939121435](https://github.com/gitboyzcf/vite-plugin-style-vw-loader/assets/9654867/de9e6646-29d8-4e0f-a676-5009da6b0915)

**Comment by gitboyzcf** [comment]
感谢提出，该问题已修复（删除该包，重新下载就行了）
