### ISSUE TITLE
配置完成之后无效

### ISSUE THREAD

**Issue by helloQAQdingpeng** [gitboyzcf/vite-plugin-style-vw-loader#4]
plugins: [vitePluginStyleVwLoader(), vue()];

配置之后没有生效的,检查下你的vitePluginStyleVwLoader是否放在vue()之前?

**Comment by gitboyzcf** [comment]
我这里安装可以，确保此插件在vue之前 `plugins: [vitePluginStyleVwLoader(), vue()]`,
