### ISSUE TITLE
把我原子化中class的text-28px 也给转换了

### ISSUE THREAD

**Issue by cq112233** [gitboyzcf/vite-plugin-style-vw-loader#7]
![WX20240528-115732](https://github.com/gitboyzcf/vite-plugin-style-vw-loader/assets/60339251/11882aea-83be-45ce-976f-5c40472e549c)

**Comment by cq112233** [comment]
https://github.com/cq112233/vite-plugin-style-to-vw/issues

**Comment by gitboyzcf** [comment]
已解决 请安装最新包   ```pnpm install vite-plugin-style-vw-loader@latest -D```
